---
  github_organisations:
  - sanger-pathogens
  - wtsi-hgi
  - sanger-sequence-assembly
  - wtsi-ssg
  - wtsi-medical-genomics
  - wtsi-clarity
  - wtsi-web
  - sanger
  - wtsi-npg
  - Anacode
  - VertebrateResequencing
  - samtools
  - cancerit
